spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stage3_module5
    username: postgres
    password: root

